version: '3.8'

services:
  web:
    build: ./project

    ports:
      - 8004:8000

    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test

    volumes:
      - ./project:/usr/src/app

    # reload enables auto reload so the server will restart after changes are made to the code base.
    # workers 1 provides a single worker process.
    # host 0.0.0.0 defines the address to host the server on.
    # port 8000 defines the port to host the server on.
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000

  web-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile

    expose:
      - 5432

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres